[package]
name = "unfeature"
description = "Expand rust features"
version = "0.1.0"
edition = "2018"

[dependencies]
syn = { version = "2.0", features = ["full", "visit", "extra-traits"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"]}
regex = "1.11"
